In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv(r"C:\Users\SAKTHI\Desktop\myproject\EMI Predict AI\data\emi_prediction_dataset.csv")

C:\Users\SAKTHI\AppData\Local\Temp\ipykernel_24724\3187611280.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\SAKTHI\Desktop\myproject\EMI Predict AI\data\emi_prediction_dataset.csv")

In [13]:
df.head(5)

,age,gender,marital_status,education,monthly_salary,employment_type,years_of_employment,company_type,house_type,monthly_rent,family_size,dependents,school_fees,college_fees,travel_expenses,groceries_utilities,other_monthly_expenses,existing_loans,current_emi_amount,credit_score,bank_balance,emergency_fund,emi_scenario,requested_amount,requested_tenure,emi_eligibility,max_monthly_emi
0,38.0,Female,Married,Professional,82600.0,Private,0.9,Mid-size,Rented,20000.0,3,2,0.0,0.0,7200.0,19500.0,13200.0,Yes,23700.0,660.0,303200.0,70200.0,Personal Loan EMI,850000.0,15,Not_Eligible,500.0
1,38.0,Female,Married,Graduate,21500.0,Private,7.0,MNC,Family,0.0,2,1,5100.0,0.0,1400.0,5400.0,3500.0,Yes,4100.0,714.0,92500.0,26900.0,E-commerce Shopping EMI,128000.0,19,Not_Eligible,700.0
2,38.0,Male,Married,Professional,86100.0,Private,5.8,Startup,Own,0.0,4,3,0.0,0.0,10200.0,19400.0,6000.0,No,0.0,650.0,672100.0,324200.0,Education EMI,306000.0,16,Eligible,27775.0
3,58.0,Female,Married,High School,66800.0,Private,2.2,Mid-size,Own,0.0,5,4,11400.0,0.0,6200.0,11900.0,7900.0,No,0.0,685.0,440900.0,178100.0,Vehicle EMI,304000.0,83,Eligible,16170.0
4,48.0,Female,Married,Professional,57300.0,Private,3.4,Mid-size,Family,0.0,4,3,9400.0,21300.0,3600.0,16200.0,8100.0,No,0.0,770.0,97300.0,28200.0,Home Appliances EMI,252000.0,7,Not_Eligible,500.0

In [6]:
df.shape

(404800, 27)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404800 entries, 0 to 404799
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   age                     404800 non-null  object
 1   gender                  404800 non-null  object
 2   marital_status          404800 non-null  object
 3   education               402396 non-null  object
 4   monthly_salary          404800 non-null  object
 5   employment_type         404800 non-null  object
 6   years_of_employment     404800 non-null  float64
 7   company_type            404800 non-null  object
 8   house_type              404800 non-null  object
 9   monthly_rent            402374 non-null  float64
 10  family_size             404800 non-null  int64
 11  dependents              404800 non-null  int64
 12  school_fees             404800 non-null  float64
 13  college_fees            404800 non-null  float64
 14  travel_expenses         404800 non-null  float64
 15  groceries_utilities     404800 non-null  float64
 16  other_monthly_expenses  404800 non-null  float64
 17  existing_loans          404800 non-null  object
 18  current_emi_amount      404800 non-null  float64
 19  credit_score            402380 non-null  float64
 20  bank_balance            402374 non-null  object
 21  emergency_fund          402449 non-null  float64
 22  emi_scenario            404800 non-null  object
 23  requested_amount        404800 non-null  float64
 24  requested_tenure        404800 non-null  int64
 25  emi_eligibility         404800 non-null  object
 26  max_monthly_emi         404800 non-null  float64
dtypes: float64(12), int64(3), object(12)
memory usage: 83.4+ MB

In [7]:
object_cols = df.select_dtypes('object').columns
object_cols

Index(['age', 'gender', 'marital_status', 'education', 'monthly_salary',
       'employment_type', 'company_type', 'house_type', 'existing_loans',
       'bank_balance', 'emi_scenario', 'emi_eligibility'],
      dtype='object')

In [ ]:
#age object -- num
# monthly_salary object -- num
# bank_balance object -- num

In [14]:
df['age'].unique()

array([38.0, 58.0, 48.0, 32.0, 27.0, 47.0, 37.0, 31.0, 59.0, 49.0, 33.0,
       26.0, 39.0, 57.0, 28.0, '58', '38', '48', '32', '27', '37', '48.0',
       '33', '38.0', '49', '27.0', '31', '39', '47', '59', '32.0', '58.0',
       '57', '26', '28', '58.0.0', '39.0', '26.0', '37.0', '38.0.0',
       '32.0.0'], dtype=object)

In [23]:
df['age'].unique()

array([38, 58, 48, 32, 27, 47, 37, 31, 59, 49, 33, 26, 39, 57, 28])

In [4]:

df['gender'].unique()

array(['Female', 'Male', 'female', 'male', 'M', 'MALE', 'F', 'FEMALE'],
      dtype=object)

In [32]:
pd.DataFrame({
    "column": df.columns,
    "data_type": [df[col].dtype for col in df.columns],
    "unique_count": [df[col].nunique() for col in df.columns],
    "sample_unique_values": [
        df[col].unique()[:10] for col in df.columns
    ]
})

,column,data_type,unique_count,sample_unique_values
0,age,int64,15,"[38, 58, 48, 32, 27, 47, 37, 31, 59, 49]"
1,gender,object,2,"[Female, Male]"
2,marital_status,object,2,"[Married, Single]"
3,education,object,4,"[Professional, Graduate, High School, Post Gra..."
4,monthly_salary,float64,8449,"[8.0, 2.0, 6.0, 5.0, 3.0, 3944.0, 4.0, 12.0, 1..."
5,employment_type,object,3,"[Private, Government, Self-employed]"
6,years_of_employment,float64,356,"[0.9, 7.0, 5.8, 2.2, 3.4, 5.0, 36.0, 12.9, 1.9..."
7,company_type,object,5,"[Mid-size, MNC, Startup, Large Indian, Small]"
8,house_type,object,3,"[Rented, Family, Own]"
9,monthly_rent,float64,4396,"[20000.0, 0.0, 13500.0, 13100.0, 11700.0, 1760..."
10,family_size,int64,5,"[3, 2, 4, 5, 1]"
11,dependents,int64,5,"[2, 1, 3, 4, 0]"
12,school_fees,float64,132,"[0.0, 5100.0, 11400.0, 9400.0, 10200.0, 15000...."
13,college_fees,float64,202,"[0.0, 21300.0, 24100.0, 11300.0, 8900.0, 15300..."
14,travel_expenses,float64,284,"[7200.0, 1400.0, 10200.0, 6200.0, 3600.0, 3400..."
15,groceries_utilities,float64,544,"[19500.0, 5400.0, 19400.0, 11900.0, 16200.0, 8..."
16,other_monthly_expenses,float64,373,"[13200.0, 3500.0, 6000.0, 7900.0, 8100.0, 6700..."
17,existing_loans,object,2,"[Yes, No]"
18,current_emi_amount,float64,508,"[23700.0, 4100.0, 0.0, 9900.0, 33100.0, 7100.0..."
19,credit_score,float64,427,"[660.0, 714.0, 650.0, 685.0, 770.0, 792.0, 741..."
20,bank_balance,float64,10614,"[303200.0, 92500.0, 672100.0, 440900.0, 97300...."
21,emergency_fund,float64,5486,"[70200.0, 26900.0, 324200.0, 178100.0, 28200.0..."
22,emi_scenario,object,5,"[Personal Loan EMI, E-commerce Shopping EMI, E..."
23,requested_amount,float64,1491,"[850000.0, 128000.0, 306000.0, 304000.0, 25200..."
24,requested_tenure,int64,82,"[15, 19, 16, 83, 7, 53, 11, 12, 14, 3]"
25,emi_eligibility,object,3,"[Not_Eligible, Eligible, High_Risk]"
26,max_monthly_emi,float64,15383,"[500.0, 700.0, 27775.0, 16170.0, 1950.0, 8260...."

In [36]:
print("After Cleaning:")
print(df.isnull().sum().sum(), "missing values remaining.")
print("Shape after cleaning:", df.shape)

After Cleaning:
28705 missing values remaining.
Shape after cleaning: (404800, 27)

In [ ]:
df.isnull().sum()

age                           0
gender                        0
marital_status                0
education                  2404
monthly_salary            14712
employment_type               0
years_of_employment           0
company_type                  0
house_type                    0
monthly_rent               2426
family_size                   0
dependents                    0
school_fees                   0
college_fees                  0
travel_expenses               0
groceries_utilities           0
other_monthly_expenses        0
existing_loans                0
current_emi_amount            0
credit_score               2420
bank_balance               4392
emergency_fund             2351
emi_scenario                  0
requested_amount              0
requested_tenure              0
emi_eligibility               0
max_monthly_emi               0
dtype: int64

In [44]:
(df['monthly_salary'].isnull().sum()/len(df['monthly_salary']))*100

np.float64(3.6343873517786562)

In [46]:
df[df["monthly_salary"] <= 0].shape

(37043, 27)

In [7]:
import pandas as pd

df = pd.read_csv(r"C:\Users\SAKTHI\Desktop\myproject\EMI Predict AI\data\target_dataset.csv")

In [8]:
df.head(5)

   emi_eligibility  max_monthly_emi
0                2            500.0
1                2            700.0
2                0          27775.0
3                0          16170.0
4                2            500.0

In [10]:
import pandas as pd

df = pd.read_csv(r"C:\Users\SAKTHI\Desktop\myproject\EMI Predict AI\data\feature_dataset.csv")
pd.set_option('display.max_columns', None)

In [12]:
df.isnull().sum()

gender_Female                              0
gender_Male                                0
marital_status_Married                     0
marital_status_Single                      0
education_Graduate                         0
education_High School                      0
education_Post Graduate                    0
education_Professional                     0
employment_type_Government                 0
employment_type_Private                    0
employment_type_Self-employed              0
company_type_Large Indian                  0
company_type_MNC                           0
company_type_Mid-size                      0
company_type_Small                         0
company_type_Startup                       0
house_type_Family                          0
house_type_Own                             0
house_type_Rented                          0
existing_loans_No                          0
existing_loans_Yes                         0
emi_scenario_E-commerce Shopping EMI       0
emi_scenario_Education EMI                 0
emi_scenario_Home Appliances EMI           0
emi_scenario_Personal Loan EMI             0
emi_scenario_Vehicle EMI                   0
age                                        0
monthly_salary                          1993
years_of_employment                        0
monthly_rent                               0
family_size                                0
dependents                                 0
school_fees                                0
college_fees                               0
travel_expenses                            0
groceries_utilities                        0
other_monthly_expenses                     0
current_emi_amount                         0
credit_score                               0
bank_balance                               0
emergency_fund                             0
requested_amount                           0
requested_tenure                           0
total_expenses                             0
disposable_income                       1993
debt_to_income                          1993
expense_ratio                           1993
estimated_new_emi                          0
emi_to_income_ratio                     1993
savings_rate                            1993
emergency_coverage                         0
Salary_per_dependent                    1993
credit_risk_band                           0
dtype: int64

In [17]:
import pandas as pd

df = pd.read_csv(r"C:\Users\SAKTHI\Desktop\myproject\EMI Predict AI\data\feature_dataset.csv")
pd.set_option('display.max_columns', None)

In [18]:
df.isnull().sum()

gender_Female                           0
gender_Male                             0
marital_status_Married                  0
marital_status_Single                   0
education_Graduate                      0
education_High School                   0
education_Post Graduate                 0
education_Professional                  0
employment_type_Government              0
employment_type_Private                 0
employment_type_Self-employed           0
company_type_Large Indian               0
company_type_MNC                        0
company_type_Mid-size                   0
company_type_Small                      0
company_type_Startup                    0
house_type_Family                       0
house_type_Own                          0
house_type_Rented                       0
existing_loans_No                       0
existing_loans_Yes                      0
emi_scenario_E-commerce Shopping EMI    0
emi_scenario_Education EMI              0
emi_scenario_Home Appliances EMI        0
emi_scenario_Personal Loan EMI          0
emi_scenario_Vehicle EMI                0
Unnamed: 0                              0
age                                     0
monthly_salary                          0
years_of_employment                     0
monthly_rent                            0
family_size                             0
dependents                              0
school_fees                             0
college_fees                            0
travel_expenses                         0
groceries_utilities                     0
other_monthly_expenses                  0
current_emi_amount                      0
credit_score                            0
bank_balance                            0
emergency_fund                          0
requested_amount                        0
requested_tenure                        0
total_expenses                          0
disposable_income                       0
debt_to_income                          0
expense_ratio                           0
estimated_new_emi                       0
emi_to_income_ratio                     0
savings_rate                            0
emergency_coverage                      0
salary_per_dependent                    0
credit_risk_band                        0
dtype: int64

In [19]:
import pandas as pd

df = pd.read_csv(r"C:\Users\SAKTHI\Desktop\myproject\EMI Predict AI\data\target_dataset.csv")

In [20]:
df.head()

   emi_eligibility  max_monthly_emi
0                2            500.0
1                2            700.0
2                0          27775.0
3                0          16170.0
4                2            500.0